remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "ðŸ”‹"
description: "This project focuses on the relationship between power outage cause, duration, and other related information to predict and prevent major power outages in the future."
